### ISSUE TITLE
Fix 5 pre-existing test failures in CI

### ISSUE THREAD

**Issue by derrring** [derrring/MFG_PDE#600]
## Summary

5 tests are failing in CI on `main` branch (pre-existing, not caused by recent PRs). These failures prevent CI from running newer tests due to `--maxfail=5` configuration.

## Failing Tests

Verified failing on `main` branch commit `4f3150af` (2026-01-18):

### 1. Integration Test: Solution Smoothness
**Test**: `tests/integration/test_fdm_solvers_mfg_complete.py::TestFDMSolversNumericalProperties::test_solution_smoothness`

**Error**:
```
AssertionError: Solution shows wild oscillations
assert np.float64(2281.107475331515) < 2000.0
```

**Cause**: HJB-FP solver produces oscillations exceeding smoothness threshold (2281 > 2000)

**Severity**: HIGH - Indicates potential numerical instability in MFG solver

---

### 2-3. Integration Tests: FP GFDM Drift Field Shape

**Tests**:
- `tests/integration/test_particle_collocation_mfg.py::TestFPGFDMSolver::test_fp_gfdm_outputs_on_collocation_points`
- `tests/integration/test_particle_collocation_mfg.py::TestFPGFDMSolver::test_fp_gfdm_mass_conservation`

**Error**:
```
ValueError: drift_field shape (21, 100) must be (21, 100, 2) (Nt+1=21, N=100, d=2)
```

**Cause**: drift_field expects 3D array `(Nt+1, N, d)` but receiving 2D array `(Nt+1, N)`

**Severity**: MEDIUM - GFDM collocation tests broken, but FDM tests working

---

### 4-5. Unit Tests: Experiment Manager Mock Issue

**Tests**:
- `tests/unit/test_experiment_manager.py::test_save_experiment_data_basic`
- `tests/unit/test_experiment_manager.py::test_save_experiment_data_filename_components`

**Error**:
```
TypeError: MockMFGProblem.__init__() got an unexpected keyword argument 'geometry'
```

**Cause**: MockMFGProblem test fixture doesn't accept `geometry` kwarg (likely outdated after API changes)

**Severity**: LOW - Test infrastructure issue, not production code

---

## Impact

**CI Pipeline**: `--maxfail=5` stops after these 5 failures, preventing newer tests from running
**Workaround**: Tests can be run locally or skip these specific tests in CI

## Reproduction

```bash
# All 5 tests fail on main branch
git checkout main
pytest tests/integration/test_fdm_solvers_mfg_complete.py::TestFDMSolversNumericalProperties::test_solution_smoothness -v
pytest tests/integration/test_particle_collocation_mfg.py::TestFPGFDMSolver -v
pytest tests/unit/test_experiment_manager.py::test_save_experiment_data_basic -v
```

## Suggested Fixes

1. **test_solution_smoothness**: Investigate HJB-FP numerical stability, possibly adjust tolerance or fix solver
2. **GFDM drift_field tests**: Update tests to provide 3D drift_field or fix GFDM API
3. **Experiment manager tests**: Update MockMFGProblem fixture to accept `geometry` parameter

## Related

- Discovered during PR #599 review
- These failures are **pre-existing**, not caused by PR #599 (verified on main)
- Blocking CI from running new test suites
